// <auto-generated />
using Ecommerce_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce_App.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Delivers the quality and refinement you've come to expect from Celviano, in a compact-yet-elegant cabinet that compliments any space ",
                            Name = "Piano",
                            Price = 1000.00m,
                            SKU = "213nvnv33"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Beautiful melodies ",
                            Name = "Fluet",
                            Price = 20.00m,
                            SKU = "33mmml23"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Has a lot a base and has been used by Jimi Hendrix ",
                            Name = "Guitar",
                            Price = 300.00m,
                            SKU = "113nvev33"
                        },
                        new
                        {
                            Id = 4,
                            Description = " Basic microphone that can be hooked up to almost anything ",
                            Name = "Microphone",
                            Price = 100.00m,
                            SKU = "200llvnv33"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Headphones designed by Dr.Dre ",
                            Name = "Beats Headphones",
                            Price = 500.00m,
                            SKU = "213nvnv44"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Studio speakers",
                            Name = "Speaker",
                            Price = 1000.00m,
                            SKU = "213oonv33"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Plastic harmonica",
                            Name = "Harmonica",
                            Price = 5.00m,
                            SKU = "122pppp222"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gold and diamond harp with silk strings",
                            Name = "Harp",
                            Price = 10000.00m,
                            SKU = "213dddd33"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Black and Gold and comes with speaker",
                            Name = "Electric Guitar",
                            Price = 750.00m,
                            SKU = "199rrnv33"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Full drum set",
                            Name = "Drum",
                            Price = 490.00m,
                            SKU = "213oonv00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
